import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse
from datetime import datetime
import re

# List of Wikipedia page titles
urls = [
    "Feynman diagram",
    "Physics",
    "Physicist",
    "List of physicists",
    "Phase (matter)",
    "Outline of physics",
    "Pauli exclusion principle",
    "Rayleigh scattering",
    "String theory",
    "Spacetime",
    "Spectrum",
    "Tensor",
    "Vector space",
    "Euclidean vector",
    "Virial theorem",
    "Optical axis",
    "Phase distortion",
    "Standard Model",
    "Navier–Stokes equations",
    "Conventional superconductor",
    "List of thermodynamic properties",
    "Radio-frequency induction",
    "Wave function collapse",
    "Zero-point energy",
    "Perturbation theory",
    "Nonlinear system",
    "List of letters used in mathematics, science, and engineering",
    "Noether's theorem",
    "Causality (physics)",
    "Shortwave radiation (optics)",
    "Turbulence",
    "Naïve physics",
    "Maxwell–Boltzmann statistics",
    "List of unsolved problems in physics",
    "Bose–Einstein statistics",
    "Phase space",
    "Virtual particle",
    "Metric tensor",
    "Supersymmetry",
    "Dynamics (mechanics)",
    "Four-vector",
    "Coherence (physics)",
    "Ergodic hypothesis",
    "Supercooling",
    "Self-organization",
    "Microscopic scale",
    "Poisson bracket",
    "Commutative property",
    "Index of optics articles",
    "Gauss gun",
    "Active and passive transformation",
    "Macroscopic scale",
    "List of particles",
    "Legendre transformation",
    "List of refractive indices",
    "Speed prior",
    "Physical Review Focus",
    "Vector potential",
    "Path integral formulation",
    "Classical limit",
    "Thermal energy",
    "Potential gradient",
    "List of moments of inertia",
    "Spatial scale",
    "List of theoretical physicists",
    "Timeline of discovery of Solar System planets and their moons",
    "Mean-field theory",
    "Action at a distance",
    "MIRACL",
    "Ship model basin",
    "List of string theory topics",
    "Spatial resolution",
    "Linear system",
    "List of physical quantities",
    "List of publications in physics",
    "List of Slovenian physicists",
    "Modern physics",
    "Complementary experiments",
    "First principle",
    "Node (physics)",
    "Curved spacetime",
    "For all practical purposes",
    "Negative frequency",
    "McLeod gauge",
    "Network automaton",
    "Eightfold way (physics)",
    "Physics and Astronomy Classification Scheme",
    "Point particle",
    "Heim theory",
    "Free particle",
    "List of states of matter",
    "Ansatz",
    "Mandelstam variables",
    "Crest and trough",
    "Lorenz gauge condition",
    "Physical object",
    "List of plasma physicists",
    "Wigner quasiprobability distribution",
    "Lorentz scalar",
    "Isotropic radiation",
    "Nucleation",
    "Quark model",
    "Regularization (physics)",
    "Lockhart–Martinelli parameter",
    "Carreau fluid",
    "Perfect fluid",
    "Rollin film",
    "Thermodynamic limit",
    "Narrow bipolar pulse",
    "List of mesons",
    "List of contributors to general relativity",
    "Enthalpy of atomization",
    "Contributors to the mathematical background for general relativity",
    "List of baryons",
    "Test theory",
    "Jolly balance",
    "Homogeneity (physics)",
    "Reverse diffusion",
    "Symmetry (physics)",
    "Temporal resolution",
    "Foot per second",
    "List of textbooks in thermodynamics and statistical mechanics",
    "Mechanical impedance",
    "Pressure experiment",
    "Über die von der molekularkinetischen Theorie der Wärme geforderte Bewegung von in ruhenden Flüssigkeiten suspendierten Teilchen",
    "List of accelerators in particle physics",
    "Magnetorheological finishing",
    "ISO 31-3",
    "ISO 31-4",
    "ISO 31-5",
    "ISO 31-6",
    "List of synchrotron radiation facilities",
    "Surface freezing",
    "Interface (matter)",
    "List of physics journals",
    "Stanton number",
    "NIST-7",
    "Physical coefficient",
    "List of physical constants",
    "Wigner–Weyl transform",
    "Grazing incidence diffraction",
    "Radian per second",
    "Covariant formulation of classical electromagnetism",
    "List of types of interferometers",
    "Professor of Natural Philosophy (Glasgow)",
    "Phoswich detector",
    "Henri Poincaré Prize",
    "Poincaré Seminars",
    "Karatmeter",
    "List of centroids",
    "Spin pumping",
    "Nuclear astrophysics",
    "Electron emission",
    "Bhabha scattering",
    "Effective torque",
    "Communication physics",
    "Center of curvature",
    "Atomic and molecular astrophysics",
    "Engineering science and mechanics",
    "Self-amplified spontaneous emission",
    "Phase offset modulation",
    "Ideally hard superconductor",
    "List of common physics notations",
    "Rheoscope",
    "Non-contact force",
    "List of Foucault pendulums",
    "Ground pressure",
    "Active cavity radiometer",
    "Poynting effect",
    "Superferromagnetism",
    "Pasotron",
    "List of second moments of area",
    "Ponderomotive energy",
    "Modulation sphere",
    "Lists of physics equations",
    "Equivalent dumping coefficient",
    "List of quantum-mechanical systems with analytical solutions",
    "Self-diffusion",
    "Mioara Mugur-Schächter",
    "Quantum state space",
    "Coherent potential approximation",
    "Fuel mass fraction",
    "Optical properties of water and ice",
    "Sun valve",
    "Reversible reference system propagation algorithm",
    "Townsend (unit)",
    "Conceptual physics",
    "Malter effect",
    "Classical fluid",
    "Quality (physics)",
    "Newton's theorem of revolving orbits",
    "Physical theories modified by general relativity",
    "Laplace limit",
    "List of scientific publications by Albert Einstein",
    "Middle World",
    "Fragment separator",
    "Resistive skin time",
    "Pseudo-modal energies",
    "Laser integration line",
    "Radiophysics",
    "Streaming vibration current",
    "Potentiometric surface",
    "Transmissibility (structural dynamics)",
    "Microbarometer",
    "Mass versus weight",
    "Monster (physics)",
    "Thermal emittance",
    "Nimrod (synchrotron)",
    "Zero mode",
    "Ion drift meter",
    "Orthobaric density",
    "Atomichron",
    "List of quasiparticles",
    "Beard and Chuang model",
    "Lariat chain",
    "Compressed hydrogen",
    "Rutherford cable",
    "Covariance group",
    "Constant-resistance network",
    "Shape waves",
    "Kleemenko cycle",
    "Transient friction loading",
    "Quantum pseudo-telepathy",
    "Continuum (measurement)",
    "Superglass",
    "Rotational Brownian motion",
    "Variable structure system",
    "Relativistic heat conduction",
    "Bhāskara's wheel",
    "Multiple-emitter transistor",
    "Surface stress",
    "Helical boundary conditions",
    "Stoneley wave",
    "Unwin Radar",
    "Ruze's equation",
    "Branches of physics",
    "Britney Spears' Guide to Semiconductor Physics",
    "Quasistatic approximation",
    "Inertia damper",
    "List of unusual units of measurement",
    "Submerged specific gravity",
    "Observer (quantum physics)",
    "Impedance pump",
    "Electrically scanning microwave radiometer",
    "Optical force",
    "List of Feynman diagrams",
    "Radioscope",
    "Light valve",
    "Parabola of safety",
    "Z-tube",
    "Goddard problem",
    "Clockwise",
    "Orders of magnitude (entropy)",
    "Frame-dragging",
    "List of optical illusions",
    "Super Bloch oscillations",
    "Langworthy Professor",
    "Plasmaron",
    "Characteristic length",
    "Mean inter-particle distance",
    "Matthiessen's ratio",
    "List of minerals by optical properties",
    "Physical system",
    "Laser dye",
    "PANDA experiment",
    "Spin geometry",
    "Ternary fission",
    "Pole piece",
    "Long-slit spectroscopy",
    "List of dualities",
    "Quantum non-equilibrium",
    "Radiation effect",
    "List of plasma physics articles",
    "Identity channel",
    "QED vacuum",
    "List of laser articles",
    "List of mathematical physics journals",
    "List of books on popular physics concepts",
    "BigDFT",
    "Phase conjugation",
    "Brazier effect",
    "List of heliophysics missions",
    "LARMOR neutron microscope",
    "Relative locality",
    "List of physics concepts in primary and secondary education curricula",
    "Moisture expansion",
    "Generalized Lagrangian mean",
    "MinutePhysics",
    "Nodary",
    "Snowden (physics)",
    "Foot per second squared",
    "Asymptotic safety in quantum gravity",
    "Edison Volta Prize",
    "Index of physics articles",
    "Inherent viscosity",
    "Vibroscope",
    "Terradynamics",
    "Gouy phase shift",
    "List of textbooks in electromagnetism",
    "Super-Poissonian distribution",
    "Specific mechanical energy",
    "Specific potential energy",
    "Flotation of flexible objects",
    "Proof mass",
    "Extinction paradox",
    "Laser printing of single nanoparticles",
    "Hemihelix",
    "Dynamic amplification factor",
    "Coherent turbulent structure",
    "Sznajd model",
    "Atmospheric-pressure photoionization",
    "Polynomial Wigner–Ville distribution",
    "Birds in a truck riddle",
    "List of physics mnemonics",
    "Magnes the shepherd",
    "Liquid whistle",
    "High-confinement mode",
    "Hyperuniformity",
    "List of gravitational wave observations",
    "Nanomechanical resonator",
    "Three Physicists Prize",
    "XMASS",
    "Nonadiabatic transition state theory",
    "Bregman Lagrangian",
    "K band (infrared)",
    "Vector quantity",
    "Front (physics)",
    "M5-brane",
    "List of scattering experiments",
    "Liquid slugging",
    "Time-translation symmetry",
    "Curie's principle",
    "List of Proton Synchrotron experiments",
    "Contracted Bianchi identities",
    "Robophysics",
    "List of American Physical Society prizes and awards",
    "Orders of magnitude (angular momentum)",
    "Frank–Van der Merwe growth",
    "Single particle extinction and scattering",
    "List of textbooks on classical mechanics and quantum mechanics",
    "Entanglement monotone",
    "Unification of theories in physics",
    "Rolf Wideroe Prize",
    "Mercier criterion",
    "Tensor network",
    "Station of Extreme Light",
    "Gravitational contact terms",
    "Scott X. Mao",
    "Classical probability density",
    "Electron quadruplets",
    "Bayshore Resilience",
    "Norwegian Physical Society",
    "Nanophotonic scintillators",
    "Phase space crystal",
    "Exceptional point",
    "List of conversion factors",
    "Hegerfeldt's theorem",
    "List of textbooks in physics",
    "List of atmospheric optical phenomena",
    "Toroidal solenoid",
    "List of dimensionless numbers in fluid mechanics",
    "Commensurability (physics)",
    "List of CERN Scientific Committees",
    "Edge states",
    "List of experiments in physics",
    "Quasi-isodynamic stellarator",
    "David Ritchie (physicist)",
    "Hawking's time traveller party",
    "Shockwave cosmology",
    "Electrofreezing",
    "Boronization",
    "Landau derivative",
    "Zeldovich regularization",
    "Radiation-enhanced diffusion",
    "Dicalcium ruthenate",
    "GS-NDG-9422",
    "Bijel",
    "Donald R. Hamann",
    "Electrostatic solitary wave",
    "List of textbooks on relativity",
    "Nottingham effect",
    "Solar wind turbulence",
    "History of the LED",
    "Zirconium silicon sulfide",
    "Pressure-wind relationship calculations for tropical cyclones",
    "Missile lofting",
    "List of hypothetical particles",
    "Wohlfarth Lectureship",
    "Gator (facility)",
    "Bitensor",
    "List of second-generation physicists"
    "Assembly_language",
    "Kolmogorov_complexity",
    "Bra–ket_notation",
    "Software",
    "Computer_science",
    "Claude_Shannon",
    "Computer_program",
    "List_of_computer_scientists",
    "Church–Turing_thesis",
    "Debit_card",
    "Elementary_function",
    "Horner's_method",
    "Information_theory",
    "Entropy_(information_theory)",
    "Knowledge_Systems_Laboratory",
    "IMU_Abacus_Medal",
    "OSGi",
    "Timeline_of_programming_languages",
    "Quantum_computing",
    "RFPolicy",
    "String_(computer_science)",
    "Software_Engineering_Body_of_Knowledge",
    "SIGGRAPH",
    "Network_throughput",
    "Time-sharing",
    "Turing_Award",
    "Nyquist–Shannon_sampling_theorem",
    "Open_system_(computing)",
    "Logic_analyzer",
    "Connectionless_communication",
    "Degree_of_isochronous_distortion",
    "Hamming_distance",
    "Link_level",
    "Systems_design",
    "Packet_switching",
    "Lua_(programming_language)",
    "ATM",
    "Embedded_system",
    "Identity_map_pattern",
    "Upload",
    "LGM-30_Minuteman",
    "Communication_complexity",
    "Reed's_law",
    "Concatenation",
    "Fast_Ethernet",
    "Computer_language",
    "Metcalfe's_law",
    "Shannon–Hartley_theorem",
    "Unicity_distance",
    "Proxy_server",
    "Pacemaker",
    "System_on_a_chip",
    "Shotgun_debugging",
    "Specification_language",
    "FOSSIL",
    "System_administrator",
    "Communication_channel",
    "Harry_Nyquist",
    "Outline_of_computer_science",
    "Ontology_Inference_Layer",
    "Scalability",
    "Remote_computer",
    "Message_switching",
    "Compile_time",
    "Rate–distortion_theory",
    "Lego_Mindstorms",
    "String_literal",
    "Web_container",
    "Boolean",
    "Network_information_system",
    "Thomas_write_rule",
    "Channel_capacity",
    "Negative_cache",
    "Power-line_communication",
    "Loebner_Prize",
    "Elimination_theory",
    "Asymptotic_equipartition_property",
    "Typical_set",
    "Dimension_of_an_algebraic_variety",
    "Curry–Howard_correspondence",
    "Dining_philosophers_problem",
    "Email_art",
    "Safety-critical_system",
    "Risch_algorithm",
    "In-circuit_emulation",
    "Flat-panel_display",
    "Structural_information_theory",
    "Mechatronics",
    "Barcode_reader",
    "WinGate",
    "Polynomial_long_division",
    "Synthetic_division",
    "Pulse_computation",
    "North_American_Network_Operators'_Group",
    "High-level_assembler",
    "Epigrams_on_Programming",
    "Content-addressable_memory",
    "Computer_scientist",
    "Industrial_data_processing",
    "Download",
    "Computer-aided_maintenance",
    "Gröbner_basis",
    "Human-readable_medium_and_data",
    "System_console",
    "Sleeping_barber_problem",
    "Jump_threading",
    "Truncation_selection",
    "Ten15",
    "Re-order_buffer",
    "Real_computation",
    "Measure-preserving_dynamical_system",
    "Digital_physics",
    "Mutual_information",
    "Evolutionary_programming",
    "SSLIOP",
    "DirectPlay",
    "International_Computer_Music_Conference",
    "Communication_source",
    "Query_language",
    "Starvation_(computer_science)",
    "Tony_Kent_Strix_award",
    "Cooperative_distributed_problem_solving",
    "Interaction_protocol",
    "Priority_inversion",
    "Sneakernet",
    "Computer_science_and_engineering",
    "Software_Engineering_2004",
    "Association_for_the_Advancement_of_Artificial_Intelligence",
    "I2P",
    "Cut-through_switching",
    "Information_content",
    "IBM_Research",
    "Stooge_sort",
    "Delimiter",
    "Simplified_Instructional_Computer",
    "Data_center",
    "Lava_flow_(programming)",
    "Computational_irreducibility",
    "Index_of_information_theory_articles",
    "Fisher_information",
    "Hostname",
    "Priority_inheritance",
    "Compile_farm",
    "HOOD_method",
    "On_the_Cruelty_of_Really_Teaching_Computer_Science",
    "JTAG",
    "Embedded_software",
    "Gödel_Prize",
    "Virtual_environment",
    "QNX4FS",
    "Network_Driver_Interface_Specification",
    "Reverse_lookup",
    "Smart_device",
    "Speedup_theorem",
    "Graph-structured_stack",
    "Buchberger's_algorithm",
    "Query_string",
    "Automatic_differentiation",
    "Suffix_tree",
    "Failover",
    "A_Mathematical_Theory_of_Communication",
    "Open_Programming_Language",
    "Empty_string",
    "Venus_Express",
    "Grace_Murray_Hopper_Award",
    "Concurrency_pattern",
    "Entropic_uncertainty",
    "Watchdog_timer",
    "Session_(computer_science)",
    "History_of_programming_languages",
    "Conditional_entropy",
    "Lambda_Papers",
    "Common_Business_Communication_Language",
    "Global_Neighborhood_Watch",
    "SURAnet",
    "EPIA",
    "Inverse_parser",
    "Skeleton_(computer_programming)",
    "Windows_domain",
    "Node_(networking)",
    "NesC",
    "Overlay_network",
    "Oaklisp",
    "Observational_equivalence",
    "CEN/XFS",
    "Two-level_scheduling",
    "Sign_bit",
    "End-to-end_delay",
    "Progressive_disclosure",
    "OOPSLA",
    "ROAM",
    "BCS_Lovelace_Medal",
    "CMS-2",
    "Interactive_kiosk",
    "Shannon's_source_coding_theorem",
    "Sturm's_theorem",
    "Programming_Language_Design_and_Implementation_(conference)",
    "Dynamic_link_matching",
    "Switched_Multi-megabit_Data_Service",
    "Suffix_array",
    "Oversampling",
    "Keepalive",
    "Embedded_HTTP_server",
    "Encrypted_function",
    "String_interning",
    "Fulkerson_Prize",
    "Here_document",
    "Automotive_navigation_system",
    "Network_simulation",
    "RapidIO",
    "International_Solid-State_Circuits_Conference",
    "Maria_(reachability_analyzer)",
    "Defining_length",
    "Load-balanced_switch",
    "Network_performance",
    "Planning_Domain_Definition_Language",
    "RuleML",
    "Entry_point",
    "SIGCOMM_Award_for_Lifetime_Contribution",
    "Uniform_information_representation",
    "Uniform_data_access",
    "Commit_(data_management)",
    "Branch_target_predictor",
    "Computing_with_words_and_perceptions",
    "Heterogeneous_network",
    "Symbolic_integration",
    "Spectral_efficiency",
    "PBASIC",
    "Timeout_(computing)",
    "RAM_image",
    "Networking_hardware",
    "QCP",
    "Rényi_entropy",
    "Degree_of_parallelism",
    "Embedded_Java",
    "Driver_wrapper",
    "Jetronic",
    "Twin_vector_quantization",
    "PC/104",
    "Surfel",
    "Architecture_description_language",
    "Prefetching",
    "Services_computing",
    "SQR",
    "Information_continuum",
    "LOM_port",
    "Bachelor_of_Information_Technology",
    "Flexible-fuel_vehicle",
    "Pseudo-LRU",
    "Local_Management_Interface",
    "Redundancy_(information_theory)",
    "Location_transparency",
    "Szemerédi_regularity_lemma",
    "IPSANET",
    "IEEE_Transactions_on_Information_Theory",
    "Very_high-level_programming_language",
    "Gerard_Salton_Award",
    "Utility_computing",
    "SIGCSE",
    "Simple_precedence_grammar",
    "FINO",
    "Simple_precedence_parser",
    "Join_selection_factor",
    "Gibbs'_inequality",
    "Bar_product",
    "Occam-π",
    "Flag_(programming)",
    "IJCAI_Computers_and_Thought_Award",
    "Fault_tolerance",
    "Attribute-oriented_programming",
    "Directory_System_Agent",
    "Computing_Research_Association",
    "New_Interfaces_for_Musical_Expression",
    "Information_flow_(information_theory)",
    "Connection-oriented_communication",
    "Vowel–consonant_synthesis",
    "Stable_storage",
    "Resultant",
    "Organizational_unit",
    "Problem_solving_environment",
    "Women_in_computing",
    "Bachelor_of_Computing",
    "A_Symbolic_Analysis_of_Relay_and_Switching_Circuits",
    "EXperimental_Computing_Facility",
    "Gas_flow_computer",
    "World_Multiconference_on_Systemics,_Cybernetics_and_Informatics",
    "Embedded_C++",
    "Inter-Language_Unification",
    "Memory_map",
    "Plug_compatible",
    "Defense_Information_System_Network",
    "Conference_on_Automated_Deduction",
    "Memory-disk_synchronization",
    "Implicit_invocation",
    "Room_synchronization",
    "Concurrency_semantics",
    "Location_information_server",
    "Persistent_programming_language",
    "Deadline-monotonic_scheduling",
    "Data_drilling",
    "Herbrand_Award",
    "Theil_index",
    "Radisys",
    "Network_browser",
    "Front-end_processor",
    "MailSlot",
    "Substring",
    "Bachelor_of_Computer_Science",
    "Registered_state_change_notification",
    "P2PTV",
    "Channel_use",
    "Systems_management",
    "IJCAI_Award_for_Research_Excellence",
    "Random_number_generation",
    "STREAMS",
    "Cellular_multiprocessing",
    "Computer_network_diagram",
    "Escuela_Superior_Latinoamericana_de_Informática",
    "Host_model",
    "Schwartz–Zippel_lemma",
    "Service-oriented_development_of_applications",
    "Program_transformation",
    "Marconi_Prize",
    "Bit_banging",
    "Algorithmic_information_theory",
    "Router_on_a_stick",
    "COSYSMO",
    "Output_compare",
    "Formula_game",
    "ClearTalk",
    "Imake",
    "Canterbury_corpus",
    "Physical_computing",
    "Satplan",
    "Paris_Kanellakis_Award",
    "List_of_computer_science_conferences",
    "Northbound_interface",
    "Secure_environment",
    "Direct_numerical_control",
    "Maximum_entropy_thermodynamics",
    "Dichotomic_search",
    "Semantic_URL_attack",
    "Kelly_criterion",
    "Software_visualization",
    "Cartesian_Perceptual_Compression",
    "Linear_network_coding",
    "Explicit_parallelism",
    "Bit-oriented_protocol",
    "IBM_WebFountain",
    "Semantic_resolution_tree",
    "Switch_virtual_interface",
    "Grammar-based_code",
    "CoSy",
    "Generalized_suffix_tree",
    "Focus-plus-context_screen",
    "Generation_gap_(pattern)",
    "ACM_Computing_Classification_System",
    "Versit_Consortium",
    "LwIP",
    "Offset_(computer_science)",
    "UFluids@Home",
    "History_of_computer_science",
    "Rough_fuzzy_hybridization",
    "Structured_content",
    "Board_support_package",
    "ProgramByDesign",
    "Map_communication_model",
    "Edge_loop",
    "Attentive_user_interface",
    "Computer_systems",
    "Damerau–Levenshtein_distance",
    "BURS",
    "Association_for_Automated_Reasoning",
    "Implicit_parallelism",
    "Out-of-band_agreement",
    "Noisy-channel_coding_theorem",
    "Motronic",
    "Timeline_of_information_theory",
    "Service_Data_Objects",
    "Differential_entropy",
    "Cost_efficiency",
    "Virtual_Object_System",
    "Home_network",
    "Knowledge_collection_from_volunteer_contributors",
    "Intel_HEX",
    "Synset",
    "DUAL_(cognitive_architecture)",
    "Tsallis_entropy",
    "Relay_channel",
    "Property_equivalence",
    "Fano's_inequality",
    "Integration_appliance",
    "Memory_organisation",
    "Comparison_of_programming_languages_(string_functions)",
    "PlanetLab",
    "Experimental_software_engineering",
    "Entrance_facility",
    "Factorization_of_polynomials",
    "Hartley_function",
    "Square-free_polynomial",
    "Network_on_a_chip",
    "Strings_(Unix)",
    "Zero_suppression",
    "ISBL",
    "Portable_object_(computing)",
    "Path_expression",
    "AP_Computer_Science_A",
    "Identification_scheme",
    "Power-on_reset",
    "Application_discovery_and_understanding",
    "Abox",
    "System_in_a_package",
    "Logic_of_information",
    "Dynamic_data",
    "Docstring",
    "AP_Computer_Science",
    "International_Conference_on_Functional_Programming",
    "Factory_Interface_Network_Service",
    "Internet_services_technology",
    "MIT_Media_Lab_Object-Based_Media",
    "Shannon–Weaver_model",
    "C-slowing",
    "Turnaround_document",
    "Host_system",
    "International_Joint_Conference_on_Automated_Reasoning",
    "Receiver_(information_theory)",
    "BOOPSI",
    "Eckert–Mauchly_Award",
    "Mail-sink",
    "Trimming_(computer_programming)",
    "Information_Systems_Professional",
    "Channel_state_information",
    "Gateway_Setup_Assistant",
    "Secure_Operations_Language",
    "Proportional_share_scheduling",
    "Prefix_(computer_science)",
    "Suffix_(computer_science)",
    "Out-of-band_data",
    "Deterministic_parsing",
    "Frank_Benford",
    "Information_dimension",
    "Open_Knowledge_Base_Connectivity",
    "EEMBC",
    "Canadian_Information_Processing_Society",
    "Bachelor_of_Software_Engineering",
    "High_Performance_Knowledge_Bases",
    "Simple_HTML_Ontology_Extensions",
    "Knuth_Prize",
    "DISCUS",
    "Log_analysis",
    "Hyper-encryption",
    "Multiseat_configuration",
    "European_Conference_on_Object-Oriented_Programming",
    "Orthogonality_(term_rewriting)",
    "Typed_assembly_language",
    "Error_exponent",
    "Modulo-N_code",
    "International_Conference_on_Very_Large_Data_Bases",
    "Test_bench",
    "Information_algebra",
    "Operability",
    "History_of_Programming_Languages_(conference)",
    "Gordon_Bell_Prize",
    "Distributed_design_patterns",
    "Multimedia_over_Coax_Alliance",
    "Knowledge_Interchange_Format",
    "Symbolic_simulation",
    "Polar_surface_area",
    "Read–modify–write",
    "Optimal_radix_choice",
    "Automatic_layout",
    "Write_barrier",
    "History_of_information_theory",
    "Information_theory_and_measure_theory",
    "Gambling_and_information_theory",
    "Karl_Küpfmüller",
    "TRANZ_330",
    "Instruction_step",
    "Storage_violation",
    "General-purpose_modeling",
    "Visual_modeling",
    "Enterprise_data_modelling",
    "Configurable_modularity",
    "International_Conference_on_Distributed_Computing_Systems",
    "Bisection_bandwidth",
    "Privilege_revocation_(computing)",
    "Ns_(simulator)",
    "IC_programming",
    "SIGSAM",
    "Critical_security_parameter",
    "Conference_on_Embedded_Networked_Sensor_Systems",
    "Bandwidth_extension",
    "Berlekamp's_algorithm",
    "Cantor–Zassenhaus_algorithm",
    "Quantities_of_information",
    "Vyatta",
    "Diebold_10xx",
    "BasicX",
    "Principles_of_attention_stress",
    "Faugère's_F4_and_F5_algorithms",
    "AIMACO",
    "The_Web_Conference",
    "Pragmatic_theory_of_information",
    "NO_CARRIER",
    "Hume_(programming_language)",
    "Operator_grammar",
    "Teller_assist_unit",
    "Abstract_rewriting_machine",
    "Incompressible_string",
    "META_II",
    "Journal_of_Symbolic_Computation",
    "International_Conference_on_Automated_Reasoning_with_Analytic_Tableaux_and_Related_Methods",
    "International_Conference_on_Logic_Programming",
    "Doo–Sabin_subdivision_surface",
    "Computer_Aided_Verification",
    "Message_Understanding_Conference",
    "Well-formed_Petri_net",
    "Tiger-BASIC",
    "Error_floor",
    "SREC_(file_format)",
    "MISRA_C",
    "Pointwise_mutual_information",
    "Security_domain",
    "Ethernet_over_USB",
    "Comparison_of_streaming_media_software",
    "Molecular_computational_identification",
    "N-jet",
    "Formation_matrix",
    "Internet_Technical_Committee",
    "C++_string_handling",
    "Constant-weight_code",
    "Total_correlation",
    "Interaction_information",
    "Scalable_TCP",
    "Reflector_(cellular_automaton)",
    "IAR_Systems",
    "Input_Field_Separators",
    "System_Fault_Tolerance",
    "Power_cycling",
    "Type_erasure",
    "Constraint_(information_theory)",
    "Shaping_codes",
    "Institute_for_Personal_Robots_in_Education",
    "Rule_induction",
    "Peptide_computing",
    "Fixed-priority_pre-emptive_scheduling",
    "Background_debug_mode_interface",
    "British_Colloquium_for_Theoretical_Computer_Science",
    "Hutter_Prize",
    "Information_Harvesting",
    "Context-aware_pervasive_systems",
    "Engine_(computer_science)",
    "Comparison_of_programming_languages_(strings)",
    "Phase_factor",
    "Stride_scheduling",
    "Nested_loop_join",
    "Microsoft_Award",
    "Maximal_pair",
    "Hardware-in-the-loop_simulation",
    "Edsger_W._Dijkstra_Prize_in_Distributed_Computing",
    "Preferential_attachment",
    "Spatial_multiplexing",
    "Left_corner",
    "Code_rate",
    "Computer-on-module",
    "Single-user_mode",
    "B5000_instruction_set",
    "Brazilian_Computer_Society",
    "Anti-hijack_system",
    "Information-based_complexity",
    "Indian_Association_for_Research_in_Computing_Science",
    "Speculative_multithreading",
    "Three-process_view",
    "Dynamic_priority_scheduling",
    "Nullary_constructor",
    "Z-channel_(information_theory)",
    "ClearSpeed",
    "Computer_and_information_science",
    "Otis_Boykin",
    "Etherloop",
    "Reciprocity_(network_science)",
    "Cockpit_display_system",
    "Gradient_network",
    "Diploma_in_Computer_Science",
    "Input/output_completion_port",
    "Native_and_foreign_format",
    "Coded_mark_inversion",
    "Recursive_join",
    "VCN_ExecuVision",
    "Chain_rule_for_Kolmogorov_complexity",
    "Pacific_Symposium_on_Biocomputing",
    "EXIT_chart",
    "Software_metering",
    "Single_version_of_the_truth",
    "David_Musser",
    "One-pass_algorithm",
    "PSI_Comp_80",
    "Integrated_Geo_Systems",
    "Producer–consumer_problem",
    "Hybrid_Scheduling",
    "Programming_by_example",
    "Stevens_Award",
    "The_COED_Project",
    "Dell_PowerConnect",
    "Ascendency",
    "ISCSI_Extensions_for_RDMA",
    "Variadic",
    "Context-adaptive_variable-length_coding",
    "Diskless_shared-root_cluster",
    "Behavioral_modeling_in_computer-aided_design",
    "Multilevel_queue",
    "Dynamic_problem_(algorithms)",
    "Expression_language",
    "Proxy_list",
    "JGroups",
    "Network_agility",
    "Log_management",
    "Informating",
    "Proteins@home",
    "Xml:tm",
    "Society_for_the_Study_of_Artificial_Intelligence_and_the_Simulation_of_Behaviour",
    "Polynomial_greatest_common_divisor",
    "Intelligent_Systems_for_Molecular_Biology",
    "Digifant_engine_management_system",
    "Modularity-driven_testing",
    "Observed_information",
    "International_Symposium_on_Computer_Architecture",
    "Bandelet_(computer_science)",
    "STRIDE_model",
    "Routing_protocol",
    "Network_delay",
    "Geographic_information_retrieval",
    "Barwise_Prize",
    "European_Conference_on_Information_Retrieval",
    "Responsiveness",
    "RoboMind",
    "Madcap_(project)",
    "Windows_Vista_networking_technologies",
    "Nonextensive_entropy",
    "Mortality_(computability_theory)",
    "Information_exchange",
    "Structural_risk_minimization",
    "Bachelor_of_Computer_Information_Systems",
    "SxS",
    "Gelato_Federation",
    "Eight_Ones",
    "National_Centre_for_Text_Mining",
    "String_operations",
    "Decentralized_object_location_and_routing",
    "Label_switching",
    "Open_Architecture_Computing_Environment",
    "Dynamical_system_simulation",
    "Maximum_entropy_spectral_estimation",
    "Entropy_rate",
    "Named_data_networking",
    "Automated_exception_handling",
    "Instrumentation_(computer_programming)",
    "LZRW",
    "Security_Protocols_Open_Repository",
    "Compressed_sensing",
    "HPE_OpenCall",
    "Unwired_enterprise",
    "Connection_string",
    "Relationship_extraction",
    "Flat_neighborhood_network",
    "International_Conference_on_Web_Services",
    "Trellis_quantization",
    "Sensor_node",
]

# Output file with timestamp
timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
output_file = f"cleaned_paragraphs_{timestamp}.txt"

def remove_references(text):
    """Remove bracketed references like [1], [23], etc."""
    return re.sub(r'\[\d+\]', '', text)

with open(output_file, 'w', encoding='utf-8') as f:
    for url in urls:
        try:
            full_url = f"https://en.wikipedia.org/wiki/{url}"
            response = requests.get(full_url, timeout=10)
            soup = BeautifulSoup(response.text, 'html.parser')

            # Remove unwanted tags
            for tag in soup(['script', 'style', 'sup']):
                tag.decompose()

            paragraphs = soup.find_all('p')
            f.write(f"===== {url} =====\n\n")

            for p in paragraphs:
                line = ""
                for elem in p.children:
                    if elem.name == 'a':
                        anchor_text = elem.get_text(strip=True)
                        if anchor_text:
                            line += f"[[{anchor_text}]]"
                    elif isinstance(elem, str):
                        line += elem.strip()
                line = remove_references(line)
                if line.strip():
                    f.write(line + "\n\n")

            print(f"✅ Done: {url}")

        except Exception as e:
            print(f"❌ Failed: {url} — {e}")

print(f"\n📝 Output saved to: {output_file}")
